Se actualizan fichas de botones y formularios, y se crean fichas de E…
gcba/estandares pull request #221
Opened 2023-01-26 17:35 UTC by victorianastasi

…ncabezado y Pie de pagina

- Actualización de fichas Botones y Formularios (nombres de boton checkbox y se agrega boton radio)
- Creación de fichas de encabezado y pie de pagina

Fichas actualizadas: https://docs.google.com/document/d/1XbWFO4LbiCB2_xm3NdQvTUpJaHKxhTjD/edit#heading=h.y90l2d5avz96

2023-01-26 19:32 UTC, Jesus1397 requested changes

2023-01-26 19:32 UTC, Jesus1397 commented on src/articles/componentes/web/paginado.mdx
>    {/* <div className="mt-3 mb-4"> */}
Elminar comentarios

2023-01-26 19:32 UTC, Jesus1397 commented on src/articles/componentes/web/encabezado.mdx
> +    <img src="/componentes/encabezado/encabezado_de_pagina.svg" alt="Encabezado" />
La identacion

2023-01-26 19:32 UTC, Jesus1397 commented on src/articles/componentes/web/paso-a-paso.mdx
> +<div className="paso-a-paso-box ">
Eliminar el espaciado xd

2023-01-26 19:32 UTC, Jesus1397 commented on src/articles/componentes/web/pie-de-pagina.mdx
> +    <img src="/componentes/pie-de-pagina/pie_de_pagina.svg" alt="Pie de Página" />
Identacion

2023-01-30 18:50 UTC, lautarorodriguez96 approved these changes

2023-01-30 18:51 UTC, Jesus1397 approved these changes

2023-01-30 18:55 UTC, merged