Agregar sección de apps
gcba/estandares pull request #87
Opened 2021-01-25 15:28 UTC by guidobonomini

2021-01-29 04:18 UTC, nirougi requested changes
Van algunos comentarios respecto a los contenidos y además agregué algunos comentarios contextuales.

1. Lo que estamos agregando es algo general y no tan específico de componentes, deberíamos analizar si crear una nueva sección o modificar el nombre de componentes a otro más abarcativo. @Vpappacena, ¿qué te parece?
2. Hay varias palabras que están en inglés y que sí tienen traducciones como `mobile` o `web services`. En la sección [comunicar con claridad](https://gcba.github.io/estandares/contenido/comunicar-con-claridad/#%C2%BFcu%C3%A1ndo-usamos-jerga-y-tecnicismos) explica cómo hacer también con términos que no tienen traducción.

Haría esos ajustes antes de publicarlo.

2021-01-29 04:18 UTC, nirougi commented on src/articles/componentes/apps/iconos.mdx
> +position: 5
Falta la descripción.

2021-01-29 04:18 UTC, nirougi commented on src/articles/componentes/apps/tipos.mdx
> +Según la naturaleza del negocio del activo se definen tres tipos:
Dice que hay tres tipos pero solo lista dos.

2021-01-29 04:18 UTC, nirougi commented on src/articles/componentes/apps.mdx
>  position: 2
Habría que ajustar la descripción porque no coincide con el contenido.

2021-02-01 15:16 UTC, guidobonomini commented
@nirougi Podrías volver a revisar el PR porfa? Ya arreglé lo que comentaste y lo deje en otra sección que convenimos con Vani

2021-02-02 00:24 UTC, nirougi approved these changes

2021-02-02 00:27 UTC, nirougi commented
@guidobonomini Listo! Hacete el merge a master y ya se publica.

2021-02-04 13:04 UTC, merged