Creación ficha de componente Modals
gcba/estandares pull request #99
Opened 2021-02-08 23:32 UTC by techlowiec

Falta agregar "Tipografía" y completar "Diseño y Estructura".

2021-03-16 03:03 UTC, nirougi commented
@techlowiec de esto faltaba terminar de hacer unos ajustes, verdad?

2021-04-21 12:58 UTC, nirougi requested changes
Te dejé dos comentarios de cositas que habría que ajustar antes, el resto está perfecto!

2021-04-21 12:58 UTC, nirougi commented on src/articles/componentes/web/modals.mdx
> +description: Los modales muestran información importante que los usuarios deben reconocer. Pueden ser perjudiciales porque requieren que los usuarios tomen una acción antes de que puedan continuar in
Fijate que cambió la descripción.

2021-04-21 12:58 UTC, nirougi commented on src/articles/componentes/web/modals.mdx
> +<div
Este ejemplo quedó viejo.

2021-04-22 01:46 UTC, nirougi approved these changes
La ficha quedó bien, pero los estilos del modal todavía no corresponden bien a lo que debería ser. Tenemos que aplicar esos cambios a Obelisco.

Al ser una ficha nueva, vería de hacer eso primero antes de publicar estos cambios así evitamos subir algo que no está del todo correcto.

2021-04-22 01:52 UTC, techlowiec commented
Vi lo mismo: el contenido es lo que está en la ficha pero los estilos actuales de Obelisco son de una versión previa. Adhiero a que todo esté en sintonía antes de subir.

2021-05-13 21:20 UTC, merged